version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile # Specifying the Dockerfile to use
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "80:3000"
#     networks:
#       - web
#   nginx:
#     image: nginx
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf
#       - /etc/letsencrypt:/etc/letsencrypt
#     depends_on:
#       - app
#     networks:
#       - web
# networks:
#   web:
#     driver: bridge
